In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('onroad_5.csv')
df

C:\Users\zapate\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,state_and_county_fips_code,tribal_name,st_usps_cd,county_name,data_category_cd,scc,emissions_type_code,aircraft_engine_type_cd,emissions_op_type_code,data_set_short_name,pollutant_cd,description,total_emissions,uom
0,39077,NaN,OH,Huron,ON,2201000062,NaN,NaN,NaN,2011EPAMOVES2014,100414,Ethyl Benzene,2196.220000,LB
1,26107,NaN,MI,Mecosta,ON,2201000062,NaN,NaN,NaN,2011EPAMOVES2014,100414,Ethyl Benzene,1519.628000,LB
2,39153,NaN,OH,Summit,ON,2201000062,NaN,NaN,NaN,2011EPAMOVES2014,100414,Ethyl Benzene,4330.100000,LB
3,26083,NaN,MI,Keweenaw,ON,2201000062,NaN,NaN,NaN,2011EPAMOVES2014,100414,Ethyl Benzene,152.088000,LB
4,18057,NaN,IN,Hamilton,ON,2201000062,NaN,NaN,NaN,2011EPAMOVES2014,100414,Ethyl Benzene,7502.060000,LB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
533890,18145,NaN,IN,Shelby,ON,2203420080,NaN,NaN,NaN,2011EPAMOVES2014,VOC,Volatile Organic Compounds,0.049379,TON
533891,18143,NaN,IN,Scott,ON,2203420080,NaN,NaN,NaN,2011EPAMOVES2014,VOC,Volatile Organic Compounds,0.026357,TON
533892,17167,NaN,IL,Sangamon,ON,2203420080,NaN,NaN,NaN,2011EPAMOVES2014,VOC,Volatile Organic Compounds,0.117862,TON
533893,39167,NaN,OH,Washington,ON,2203420080,NaN,NaN,NaN,2011EPAMOVES2014,VOC,Volatile Organic Compounds,0.043313,TON
533894,27113,NaN,MN,Pennington,ON,2203420080,NaN,NaN,NaN,2011EPAMOVES2014,VOC,Volatile Organic Compounds,0.059189,TON

In [4]:
df['description'].unique()

array(['Ethyl Benzene', 'Styrene', '1,3-Butadiene', 'Acrolein', 'Toluene',
       'Hexane', 'Anthracene', 'Propionaldehyde', 'Pyrene',
       'Xylenes (Mixed Isomers)', 'Chromium (VI)',
       'Benzo[g,h,i,]Perylene', 'Indeno[1,2,3-c,d]Pyrene',
       'Benzo[b]Fluoranthene', 'Fluoranthene', 'Benzo[k]Fluoranthene',
       'Acenaphthylene', 'Chrysene', 'Formaldehyde', 'Benzo[a]Pyrene',
       'Dibenzo[a,h]Anthracene', '2,2,4-Trimethylpentane',
       'Benz[a]Anthracene', 'Benzene', 'Manganese', 'Mercury', 'Nickel',
       'Arsenic', 'Acetaldehyde', 'Acenaphthene', 'Phenanthrene',
       'Fluorene', 'Naphthalene', 'Methane', 'Carbon Monoxide',
       'Carbon Dioxide', 'Nitrous Oxide', 'Ammonia', 'Nitrogen Oxides',
       'PM10 Primary (Filt + Cond)', 'PM2.5 Primary (Filt + Cond)',
       'Sulfur Dioxide', 'Volatile Organic Compounds'], dtype=object)