Goals of this script 
1. Function that performs squre root transformation any column 
2. Function that takes a column of data, and creates an array of lag-1

In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 500)

import sklearn
import seaborn as sns
from sklearn import preprocessing
from sklearn import decomposition
from sklearn.preprocessing import MinMaxScaler
from matplotlib import pyplot as plt

import statsmodels.api as sm
import pylab

In [5]:
df_all_pm = pd.read_csv('df_all_pm_7_28.csv', index_col = 0)

In [6]:
df_all_pm

,STATE_CODE,COUNTY_CODE,YEAR,VMT,POPULATION,TOTAL_EMISSIONS,True_GDP,True_Fips,Unemployment_Rate,Charging_Stations,LNMILES,TMS,TELEWORK,distributed_UPT,GEMS_Typo,USDA_UIC
0,1,1,2000,2.744493e+08,44021.0,NaN,NaN,NaN,0.041,0.0,1980.320,NaN,NaN,NaN,F,2.0
1,1,3,2000,1.196020e+09,141342.0,NaN,NaN,NaN,0.037,0.0,4905.660,NaN,NaN,NaN,C,2.0
2,1,5,2000,1.276073e+08,29015.0,NaN,NaN,NaN,0.056,0.0,2479.120,NaN,NaN,NaN,C,6.0
3,1,7,2000,9.060923e+07,19913.0,NaN,NaN,NaN,0.054,0.0,1804.750,NaN,NaN,NaN,D,1.0
4,1,9,2000,2.181014e+08,51107.0,NaN,NaN,NaN,0.035,0.0,2763.560,NaN,NaN,NaN,D,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60809,56,37,2020,8.070806e+08,42190.0,896451.459129,3344988.0,56037.0,0.075,3.0,5252.604,0.007363,0.087175,0.0,C,8.0
60810,56,39,2020,1.738602e+08,23377.0,272610.823838,2308166.0,56039.0,0.060,21.0,1475.236,0.004938,0.112992,0.0,D,8.0
60811,56,41,2020,2.682344e+08,20457.0,341765.799203,785684.0,56041.0,0.064,1.0,1615.570,0.007363,0.087175,0.0,D,8.0
60812,56,43,2020,4.965127e+07,7658.0,64261.255841,345111.0,56043.0,0.053,0.0,1371.434,0.005502,0.053399,0.0,B,11.0
60813,56,45,2020,5.649702e+07,6818.0,65850.124831,292568.0,56045.0,0.039,0.0,1726.950,0.005502,0.053399,0.0,E,9.0

In [7]:
df_all_pm.dtypes

STATE_CODE             int64
COUNTY_CODE            int64
YEAR                   int64
VMT                  float64
POPULATION           float64
TOTAL_EMISSIONS      float64
True_GDP             float64
True_Fips            float64
Unemployment_Rate    float64
Charging_Stations    float64
LNMILES              float64
TMS                  float64
TELEWORK             float64
distributed_UPT      float64
GEMS_Typo             object
USDA_UIC             float64
dtype: object

##### Function to perform sq root transformation on any column

In [8]:
def sqrt_trans(data, col_name):
    new_col_name = col_name + '_sqrt'
    data[new_col_name] = np.sqrt(data[col_name])

In [15]:
sqrt_trans(df_all_pm, 'VMT')
sqrt_trans(df_all_pm, 'POPULATION')
sqrt_trans(df_all_pm, 'TOTAL_EMISSIONS')
sqrt_trans(df_all_pm, 'True_GDP')
sqrt_trans(df_all_pm, 'Charging_Stations')
sqrt_trans(df_all_pm, 'LNMILES')
sqrt_trans(df_all_pm, 'distributed_UPT')

In [16]:
df_all_pm

,STATE_CODE,COUNTY_CODE,YEAR,VMT,POPULATION,TOTAL_EMISSIONS,True_GDP,True_Fips,Unemployment_Rate,Charging_Stations,LNMILES,TMS,TELEWORK,distributed_UPT,GEMS_Typo,USDA_UIC,POPULATION_sqrt,TOTAL_EMISSIONS_sqrt,VMT_sqrt,True_GDP_sqrt,Charging_Stations_sqrt,LNMILES_sqrt,distributed_UPT_sqrt
0,1,1,2000,2.744493e+08,44021.0,NaN,NaN,NaN,0.041,0.0,1980.320,NaN,NaN,NaN,F,2.0,209.811820,NaN,16566.510568,NaN,0.000000,44.500787,NaN
1,1,3,2000,1.196020e+09,141342.0,NaN,NaN,NaN,0.037,0.0,4905.660,NaN,NaN,NaN,C,2.0,375.954785,NaN,34583.529028,NaN,0.000000,70.040417,NaN
2,1,5,2000,1.276073e+08,29015.0,NaN,NaN,NaN,0.056,0.0,2479.120,NaN,NaN,NaN,C,6.0,170.337899,NaN,11296.338088,NaN,0.000000,49.790762,NaN
3,1,7,2000,9.060923e+07,19913.0,NaN,NaN,NaN,0.054,0.0,1804.750,NaN,NaN,NaN,D,1.0,141.113430,NaN,9518.888023,NaN,0.000000,42.482349,NaN
4,1,9,2000,2.181014e+08,51107.0,NaN,NaN,NaN,0.035,0.0,2763.560,NaN,NaN,NaN,D,1.0,226.068574,NaN,14768.256938,NaN,0.000000,52.569573,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60809,56,37,2020,8.070806e+08,42190.0,896451.459129,3344988.0,56037.0,0.075,3.0,5252.604,0.007363,0.087175,0.0,C,8.0,205.402045,946.811206,28409.164173,1828.930835,1.732051,72.474851,0.0
60810,56,39,2020,1.738602e+08,23377.0,272610.823838,2308166.0,56039.0,0.060,21.0,1475.236,0.004938,0.112992,0.0,D,8.0,152.895389,522.121465,13185.605428,1519.264954,4.582576,38.408801,0.0
60811,56,41,2020,2.682344e+08,20457.0,341765.799203,785684.0,56041.0,0.064,1.0,1615.570,0.007363,0.087175,0.0,D,8.0,143.027969,584.607389,16377.862959,886.388177,1.000000,40.194154,0.0
60812,56,43,2020,4.965127e+07,7658.0,64261.255841,345111.0,56043.0,0.053,0.0,1371.434,0.005502,0.053399,0.0,B,11.0,87.509999,253.498039,7046.365869,587.461488,0.000000,37.032877,0.0
60813,56,45,2020,5.649702e+07,6818.0,65850.124831,292568.0,56045.0,0.039,0.0,1726.950,0.005502,0.053399,0.0,E,9.0,82.571181,256.612792,7516.450140,540.895554,0.000000,41.556588,0.0

In [17]:
df_all_pm.to_csv('df_7_31_w_sqrt_transformations.csv', index= False)

##### Function to create lag1 column for any existing column

In [55]:
def lag_col(data, col_name, n_lag):
    #create name for the lag column
    new_col_name = col_name + '_lag' + str(n_lag)
    
    #sort the data by year, group by fips code, then take the lag of the specificed 'col_name' 
    data[new_col_name] = data.sort_values(by = ['YEAR']).groupby('True_Fips')[col_name].shift(n_lag)
    return data

In [63]:
df = lag_col(df_all_pm, 'VMT', 1)
df = lag_col(df_all_pm, 'TOTAL_EMISSIONS', 1)
df = lag_col(df_all_pm, 'TOTAL_EMISSIONS', 2)
df

,STATE_CODE,COUNTY_CODE,YEAR,VMT,POPULATION,TOTAL_EMISSIONS,True_GDP,True_Fips,Unemployment_Rate,Charging_Stations,LNMILES,TMS,TELEWORK,distributed_UPT,GEMS_Typo,USDA_UIC,POPULATION_sqrt,TOTAL_EMISSIONS_sqrt,VMT_lag1,TOTAL_EMISSIONS_lag1,TOTAL_EMISSIONS_lag2
0,1,1,2000,2.744493e+08,44021.0,NaN,NaN,NaN,0.041,0.0,1980.320,NaN,NaN,NaN,F,2.0,209.811820,NaN,NaN,NaN,NaN
1,1,3,2000,1.196020e+09,141342.0,NaN,NaN,NaN,0.037,0.0,4905.660,NaN,NaN,NaN,C,2.0,375.954785,NaN,NaN,NaN,NaN
2,1,5,2000,1.276073e+08,29015.0,NaN,NaN,NaN,0.056,0.0,2479.120,NaN,NaN,NaN,C,6.0,170.337899,NaN,NaN,NaN,NaN
3,1,7,2000,9.060923e+07,19913.0,NaN,NaN,NaN,0.054,0.0,1804.750,NaN,NaN,NaN,D,1.0,141.113430,NaN,NaN,NaN,NaN
4,1,9,2000,2.181014e+08,51107.0,NaN,NaN,NaN,0.035,0.0,2763.560,NaN,NaN,NaN,D,1.0,226.068574,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60809,56,37,2020,8.070806e+08,42190.0,896451.459129,3344988.0,56037.0,0.075,3.0,5252.604,0.007363,0.087175,0.0,C,8.0,205.402045,946.811206,9.023661e+08,NaN,NaN
60810,56,39,2020,1.738602e+08,23377.0,272610.823838,2308166.0,56039.0,0.060,21.0,1475.236,0.004938,0.112992,0.0,D,8.0,152.895389,522.121465,1.842755e+08,NaN,NaN
60811,56,41,2020,2.682344e+08,20457.0,341765.799203,785684.0,56041.0,0.064,1.0,1615.570,0.007363,0.087175,0.0,D,8.0,143.027969,584.607389,2.915467e+08,NaN,NaN
60812,56,43,2020,4.965127e+07,7658.0,64261.255841,345111.0,56043.0,0.053,0.0,1371.434,0.005502,0.053399,0.0,B,11.0,87.509999,253.498039,5.165241e+07,NaN,NaN
60813,56,45,2020,5.649702e+07,6818.0,65850.124831,292568.0,56045.0,0.039,0.0,1726.950,0.005502,0.053399,0.0,E,9.0,82.571181,256.612792,6.511774e+07,NaN,NaN

In [64]:
df[(df['True_Fips'] == 56041.0)]

,STATE_CODE,COUNTY_CODE,YEAR,VMT,POPULATION,TOTAL_EMISSIONS,True_GDP,True_Fips,Unemployment_Rate,Charging_Stations,LNMILES,TMS,TELEWORK,distributed_UPT,GEMS_Typo,USDA_UIC,POPULATION_sqrt,TOTAL_EMISSIONS_sqrt,VMT_lag1,TOTAL_EMISSIONS_lag1,TOTAL_EMISSIONS_lag2
5787,56,41,2001,253674467.1,19413.0,NaN,1012685.0,56041.0,0.037,0.0,1625.448,NaN,NaN,NaN,D,8.0,139.330542,NaN,NaN,NaN,NaN
8683,56,41,2002,269686608.3,19587.0,NaN,1120573.0,56041.0,0.042,0.0,1620.948,NaN,NaN,0.0,D,8.0,139.953564,NaN,253674467.1,NaN,NaN
11579,56,41,2003,265850469.3,19480.0,NaN,1085127.0,56041.0,0.045,0.0,1615.058,NaN,NaN,0.0,D,8.0,139.570771,NaN,269686608.3,NaN,NaN
14475,56,41,2004,269005677.6,19470.0,NaN,1104145.0,56041.0,0.038,0.0,1636.798,NaN,NaN,0.0,D,8.0,139.534942,NaN,265850469.3,NaN,NaN
17371,56,41,2005,276473192.0,19494.0,NaN,1143466.0,56041.0,0.034,0.0,1635.538,NaN,NaN,0.0,D,8.0,139.620915,NaN,269005677.6,NaN,NaN
20267,56,41,2006,294637588.6,19709.0,NaN,1252369.0,56041.0,0.028,0.0,1636.546,NaN,NaN,0.0,D,8.0,140.388746,NaN,276473192.0,NaN,NaN
23163,56,41,2007,291740667.6,20171.0,NaN,1286467.0,56041.0,0.025,0.0,1621.694,NaN,NaN,0.0,D,8.0,142.024646,NaN,294637588.6,NaN,NaN
26059,56,41,2008,271478439.4,20613.0,264888.287221,1295260.0,56041.0,0.028,0.0,1621.554,NaN,NaN,0.0,D,8.0,143.572281,514.672991,291740667.6,NaN,NaN
28955,56,41,2009,NaN,21054.0,NaN,1289477.0,56041.0,0.067,0.0,1627.430,NaN,NaN,0.0,D,8.0,145.099966,NaN,271478439.4,264888.287221,NaN
31851,56,41,2010,NaN,21089.0,NaN,1215130.0,56041.0,0.076,0.0,1636.360,NaN,NaN,0.0,D,8.0,145.220522,NaN,NaN,NaN,264888.287221
34747,56,41,2011,261071872.0,20896.0,389573.787800,1076286.0,56041.0,0.066,0.0,1637.046,NaN,NaN,0.0,D,8.0,144.554488,624.158464,NaN,NaN,NaN
37643,56,41,2012,253419520.0,20996.0,NaN,1013635.0,56041.0,0.058,0.0,1899.402,0.014179,0.048516,0.0,D,8.0,144.899965,NaN,261071872.0,389573.787800,NaN
40539,56,41,2013,252235408.0,20951.0,NaN,979920.0,56041.0,0.053,0.0,1875.826,0.020930,0.033703,0.0,D,8.0,144.744603,NaN,253419520.0,NaN,389573.787800
43435,56,41,2014,258652320.0,20822.0,353522.042055,956307.0,56041.0,0.050,0.0,1879.422,0.012631,0.034098,0.0,D,8.0,144.298302,594.577196,252235408.0,NaN,NaN
46331,56,41,2015,260259984.0,20763.0,NaN,966017.0,56041.0,0.049,0.0,1881.338,0.043406,0.042206,0.0,D,8.0,144.093720,NaN,258652320.0,353522.042055,NaN
49227,56,41,2016,254895876.5,20682.0,NaN,959716.0,56041.0,0.058,0.0,1848.658,0.030431,0.046516,0.0,D,8.0,143.812378,NaN,260259984.0,NaN,353522.042055
52123,56,41,2017,264552896.4,20431.0,344398.475143,942924.0,56041.0,0.047,1.0,1537.215,0.003923,0.038567,0.0,D,8.0,142.937049,586.854731,254895876.5,NaN,NaN
55019,56,41,2018,282391907.5,20292.0,NaN,906501.0,56041.0,0.044,1.0,1689.636,0.016615,0.053363,0.0,D,8.0,142.449991,NaN,264552896.4,344398.475143,NaN
57915,56,41,2019,291546705.8,20226.0,NaN,879424.0,56041.0,0.040,1.0,1536.620,0.015955,0.056304,0.0,D,8.0,142.218142,NaN,282391907.5,NaN,344398.475143
60811,56,41,2020,268234395.1,20457.0,341765.799203,785684.0,56041.0,0.064,1.0,1615.570,0.007363,0.087175,0.0,D,8.0,143.027969,584.607389,291546705.8,NaN,NaN